export const ROLES = {
  DASHBOARD: "dashboard",
  // users ROLES

  SUPARADMINCREATE: "user/create/admin",
  MERCHENTSCREATE: "user/create/merchents",
  CREATEUSER: "user/create/user",
  USERLIST: "USERLIST",
  CREATEUSERBASICINFO: "user/create/student/:id/:name",
  CREATEUSERBASICINFOINDEX: "user/create/student/:id/:name/:level",

  //   JOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  GRADE: "GRADE",
  POST: "POST",
  DEPARTMENT: "DEPARTMENT",
  QUOTA: "QUOTA",
  JOBAPPLIED: "JOBAPPLIED",
  JOBPENDING: "JOBPENDING",

  JOBAPPLICATION: "JOBAPPLICATION",
  JOBAPPLICATIONID: "job/application/:id",
  JOBCIRCULARSTATUS: "job/circular/status/:id",
  JOBCIRCULARSTATUSCREATE: "job/circular/status/:status/create/",
  JOBCIRCULAR: "JOBCIRCULAR",
  JOBCIRCULARSTATUSUPDATE: "job/circular/status/:status/update/:id",
  MERCHENTSAPPIED: "MERCHENTSAPPIED",

  /////ADMISSION
  ADMISSIONINDEX: "ADMISSIONINDEX",
  ADMISSIONAPPLY: "ADMISSIONAPPLY",
  UNIVERSITY: "UNIVERSITY",
  UNIT: "UNIT",
  BOARD: "BOARD",
  EXAM: "EXAM",
  GROUP: "GROUP",
  PASSINGYEAR: "PASSINGYEAR",
  COURSEDURATION: "COURSEDURATION",
  SUBJECT: "SUBJECT",

  // BASIC INFOOOOOOOOOOOOOOOOOOOOOOOOOOO
  DISTRICT: "DISTRICT",
  PAYMENTWORKER: "PAYMENTWORKER",
  TERMS: "TERMS",
  POLICY: "POLICY",
};
