export const SIDEBAR = {
  DASHBOARD: "dashboard",
  // users
  USER: "user/index",
  SUPARADMINCREATE: "user/create/admin",
  MERCHENTSCREATE: "user/create/merchents",
  CREATEUSER: "user/create/:type",
  CREATEUSERADMIN: "user/create/user",

  USERLIST: "user/index",
  ALLUSERLIST: "user/all-user",
  MERCHENTLIST: "user/index/:id/:method/:system",
  MERCHENTUSERLIST: "user/merchent",

  CREATEUSERBASICINFO: "user/create/student/:id/:name",
  CREATEUSERBASICINFOINDEX: "user/create/student/:id/:name/:level",

  // jobs
  JOB: "job/grade",
  GRADE: "job/grade",
  POST: "job/post",
  DEPARTMENT: "job/department",
  QUOTA: "job/quota",
  JOBAPPLIED: "job/circular/applied",
  TRANSFERRED: "job/payement/transferred",
  JOBPENDING: "job/pending",
  JOBLISTSTATUS: "job-list/status",
  JOBAPPLICATION: "job/application",
  JOBAPPLICATIONID: "job/application/:id",
  JOBCIRCULARSTATUS: "job/circular/status/:id",
  JOBCIRCULARSTATUSCREATE: "job/circular/status/:status/create/",
  JOBCIRCULAR: "job/circular",
  JOBCIRCULARSTATUSUPDATE: "job/circular/status/:status/update/:id",
  MERCHENTSAPPIED: "job/merchent/apply",
  PAYMENTMARCHENTS: "job/payment/marchent",
  PAYMENTADMIN: "job/payment/admin",
  // admissionasddddddddddddddddddd
  UNIVERSITYCREATE: "admission/university/create",
  UNIVERSITYEDIT: "admission/university/:id/edit",
  ADMISSION: "admission/index",
  ADMISSIONINDEX: "admission/index",
  ADMISSIONEDIT: "admission/edit/:id",
  ADMISSIONCREATE: "admission/create",
  UNIT: "admission/unit",
  UNIVERSITY: "admission/university",
  BOARD: "admission/board",
  EXAM: "admission/exam",
  GROUP: "admission/group",
  COURSEDURATION: "admission/course_duration",
  SUBJECT: "admission/subject",
  PASSINGYEAR: "admission/passing_year",
  ADMISSIONAPPLIED: "admission/applied",
  ADMISSIONMERCHENTSAPPLIEDLIST: "admission/merchents/applied-list",
  ADMISSIONAPPY: "admission/status",
  SUBJECTEDIT: "admission/subject/edit/:id/:pageNo",
  ADMISSIONSTATUS: "admission/applied/:applied/status",
  ADMISSIONSTATUSCREATE: "admission/applied/:applied/status/create",
  ADMISSIONSTATUSEDIT: "admission/applied/:applied/status/:id",
  ADMISSIONAPPLY: "admission/apply/:id",

  // basic-info
  BASICINFO: "district",
  DISTRICT: "district",
  DISTRICTEDIT: "district/edit",
  UPAZILAEDIT: "district/upazila/edit/:districId/:pageNo",
  POSTOFFICE: "district/post-office/edit/:upazilaId/:pageNo",
  TERMS: "terms",
  POLICY: "policy",
  UPDATE: "update",
  PAYMENTWORKER: "payment/workers",
  PAYMENTAPPLY: "payment/apply/:module/:id/:userId",
  PAYMENTSELECT: "payment/apply/:module/:id/:userId/select",

  ROLE: "role/index",
  PERMISSION: "permission/index",
};
